### PR TITLE
support shared JavaScript utility functions (inline in dashboards.yaml or in an external file)

### PR DESCRIPTION
**Pull request by andreasgerstmayr**
Support shared JavaScript utility functions (inline in dashboards.yaml or in an external file).

**Example:**

dashboards.yaml
```
dashboards:
- name: Overview
  panels:
  - title: Example
    type: html
    script: |
      return utils.hello_world();

utils:
  path: utils.js
```

utils.js
```
function hello_world() {
  return "hello world";
}

return { hello_world };
```

Resolves: #14

### CODE REVIEW

**Comment by skfarhat** [comment]
Thanks for this! Are we considering merging it?

**Comment by andreasgerstmayr** [comment]
@skfarhat Can you give this PR a try?

You can define an external JavaScript file in `utils.path` in `dashboards.yaml` and then access it via `utils.xxx()`, for example:

dashboards.yaml
```
dashboards:
- name: Overview
  panels:
  - title: Example
    type: html
    script: |
      return utils.hello_world();

utils:
  path: utils.js
```

utils.js
```
function hello_world() {
  return "hello world";
}

return { hello_world };
```

**Comment by skfarhat** [comment]
Just did and it works, thanks!

**Comment by andreasgerstmayr** [comment]
Thanks for checking!

**Pull request merged**
